version: "3.9"

networks:
  rabbitmq-network:
    driver: bridge

services:
  mysql-8:
    image: mysql:8.0.18
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    networks:
      - rabbitmq-network  
      
  rabbitmq:
        image: rabbitmq:3.7.8-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123456    
      